spring.application.name=Discovery-Server

server.port=8761

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true


# A Eureka server is also a Eureka client by default.
# These settings tell it NOT to register with itself.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# === Monitoring: Prometheus + Actuator ===
management.endpoints.web.exposure.include=health,prometheus,info
management.metrics.tags.application=${spring.application.name}
